### ISSUE TITLE
Marker ranges are not supported?

### ISSUE THREAD

**Issue by endolith** [X-Raym/wavfile.py#7]
In Adobe Audition/Ocenaudio/REAPER, I can see markers that span a length of time, but after reading them with this function, I only see the start time.

**Comment by endolith** [comment]
I see from https://sites.google.com/site/musicgapi/technical-documents/wav-file-format#TOC-Cue-Chunk---cue- and experimenting, that this information is not in the `cue ` chunk, which only specifies the start of the cue.  I'll keep reading...

**Comment by endolith** [comment]
Ah, they're specified by https://sites.google.com/site/musicgapi/technical-documents/wav-file-format#TOC-Labeled-Text-Chunk---ltxt-  though it's `LIST`, not `list`, and their hex translation spells `lint`.

**Comment by X-Raym** [comment]
It is already possible with this code.

It powers the GUI I made there which supports cue regions insertion.

https://forum.cockos.com/showpost.php?p=2000071&postcount=20

Use RiffPad software to check wavefiles chunks and you will see how it is encoded.

**Comment by X-Raym** [comment]
Im away from computer atm so I dont have code snippet to share for now.
Using RiffPad will help you :P

**Comment by X-Raym** [comment]
Ok let me know if my integration need fixes.

**Comment by endolith** [comment]
RiffPad doesn't parse the `ltxt` chunk, either, but the segment length is visible in the hex dump (= "cue point number 3 is 5 samples long"):

![image](https://user-images.githubusercontent.com/58611/57161847-8ee18600-6dba-11e9-846b-aec3bffda5c6.png)

Purpose ID is `rgn ` (= "region"?).  Although `ltxt` also supports text labels, this is left empty and `ltxt` is only used to specify the length of the region.  `labl` is used to specify the actual text.  (Though that might only be how Audition does it.)

([I don't see a lot of documentation about what these mean](https://www.google.com/search?q="capt"+"scrp"+"rgn"+"riff").  :/ )

**Comment by endolith** [comment]
I got this working, by the way.  I'll clean it up and put it in my own fork.  Now it just outputs a single marker list for all cue-related data:

```
'markerslist': [{'position': 22583666, 'length': 2402, 'label': b'N'},
  {'position': 31389480, 'length': 0, 'label': b'R'},
  {'position': 38065320, 'length': 0, 'label': b'R'},
  {'position': 38066344, 'length': 0, 'label': b'R'},
  {'position': 38069352, 'length': 0, 'label': b'R'},
  {'position': 38069488, 'length': 0, 'label': b'R'},
  {'position': 38069610, 'length': 0, 'label': b'R'},
  {'position': 51556153, 'length': 952680, 'label': b'Cluster'},
  {'position': 53951728, 'length': 2403, 'label': b'N'},
  {'position': 85409021, 'length': 2402, 'label': b'N'},
  {'position': 116866312, 'length': 2401, 'label': b'N'},
  {'position': 148323604, 'length': 2402, 'label': b'N'},
  {'position': 179780898, 'length': 2401, 'label': b'N'},
  {'position': 211238189, 'length': 2403, 'label': b'N'}],
```

I'm not sure what to do if it specifies text in both the `labl` and `ltxt` chunks, but I haven't seen that yet.

**Comment by afparsons** [comment]
@endolith Amazing; I've just used your (incomplete?) fork and I'm happy to see the marker length extracted. :slightly_smiling_face: 

...maybe you could PR into @X-Raym 's version? Or possibly even get this into SciPy? 

Sorry for necromancing. I know very little about audio and finding this has been extremely helpful. Who knew that finding information about extracting regions would be so hard!?

**Comment by X-Raym** [comment]
@afparsons current SciPi version would be better as it got tons of enhancement on supported wav files bit depth for eg.

**Comment by afparsons** [comment]
@X-Raym Ah, I just commented [here](https://github.com/scipy/scipy/issues/6849#issuecomment-1252773058) :slightly_smiling_face:

**Comment by endolith** [comment]
@afparsons I'm trying to clean up my fork so it can go into SciPy. Any opinion on the metadata output format? I think it makes sense to just return all the metadata as a single object instead of having many different switches as parameters, but should it be a dict or namedtuple or something else?

`metadata.pitch` vs `metadata['pitch']`?

**Comment by afparsons** [comment]
> I think it makes sense to just return all the metadata as a single object instead of having many different switches as parameters

I agree. Personally, I've never liked APIs with more than one or two return switches. However, I would first poke around the SciPy codebase to figure out if they follow any sort of conventions when returning multiple values.

> but should it be a dict or namedtuple or something else?

Great question. Again, I would check for existing conventions. If there aren't any, then I would lean toward the immutable data structure (namedtuple).

I'll think about this some more, and if my opinion changes, I'll add another comment. But I believe you're spending your Saturday afternoon working on this and wanted to reply immediately :) @endolith

**Comment by endolith** [comment]
> However, I would first poke around the SciPy codebase to figure out if they follow any sort of conventions when returning multiple values.

Seems like they use several:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.OptimizeResult.html#scipy.optimize.OptimizeResult is a modified dict.

https://github.com/scipy/scipy/blob/v1.9.1/scipy/stats/_stats_py.py#L536 uses namedtuple

https://scipy.github.io/devdocs/reference/generated/scipy.signal.place_poles.html#scipy.signal.place_poles returns a Bunch object.

argument against namedtuples: https://github.com/scipy/scipy/issues/3665#issuecomment-52546370 and other discussion

We don't need tuple backwards compatibility so it makes sense to me to only support attributes.  

I'm thinking it would just be a scipy.io.wavfile.info function instead of trying to tack it onto the output of scipy.io.wavfile.read?
